import { db } from "./index";
import { products, reviews, orders, appointments } from "./schema";
import { sql } from "drizzle-orm";

export const initialProducts = [
  {
    name: "The Lowveld Bounce 28\" Wet & Wavy HD Glueless Unit",
    slug: "lowveld-bounce-wet-and-wavy-hd-glueless",
    category: "glueless-wigs",
    price: 899,
    originalPrice: 1199,
    rating: "4.9",
    reviewCount: 38,
    image: "/images/hero-hair-baddie.jpg",
    badge: "Nelspruit Best Seller 🔥",
    description: "Built for Mbombela's heat! Spray with pure water or leave-in conditioner and watch the high-definition waves spring to life. Glueless design with pre-plucked baby hairs and invisible HD Swiss lace.",
    blendDetails: "75% Virgin Cuticle Human Hair + 25% Heat-Locked Protein Silk (zero tangling, zero shedding)",
    length: "28 Inch",
    lengths: ["22 Inch", "26 Inch", "28 Inch", "32 Inch"],
    colors: ["Natural 1B Jet Black", "Warm Chestnut Brown #4", "Honey Blonde Highlights #4/27"],
    capType: "5x5 Pre-Bleached Invisible HD Glueless Lace with Elastic Security Band",
    heatLimit: "Safe up to 200°C for flat-ironing or curling tongs",
    inStock: true,
    featured: true,
  },
  {
    name: "Mbombela Bone Straight 30\" Glass Hair 13x4 Frontal Unit",
    slug: "mbombela-bone-straight-30-inch-frontal",
    category: "glueless-wigs",
    price: 980,
    originalPrice: 1350,
    rating: "5.0",
    reviewCount: 42,
    image: "https://images.pexels.com/photos/28801608/pexels-photo-28801608.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    badge: "Glass-Shine Silk ✨",
    description: "Sleek, featherweight, and completely flat down to the scalp. Glides like silk through your fingers and stays bone straight even when walking around Riverside Mall or attending weekend grooves.",
    blendDetails: "70% Steamed Human Hair + 30% Japanese Heat-Resistant Fiber for pin-straight all-day hold",
    length: "30 Inch",
    lengths: ["24 Inch", "28 Inch", "30 Inch", "34 Inch"],
    colors: ["Natural 1B Jet Black", "Espresso Chocolate #2"],
    capType: "13x4 Ear-to-Ear HD Transparent Swiss Lace Frontal",
    heatLimit: "Safe up to 200°C (Silky flat iron ready)",
    inStock: true,
    featured: true,
  },
  {
    name: "Sunset In Steiltes 24\" Copper Ginger #350 Deep Wave",
    slug: "sunset-steiltes-copper-ginger-deep-wave",
    category: "colored",
    price: 890,
    originalPrice: 1150,
    rating: "4.9",
    reviewCount: 29,
    image: "/images/hair-ginger-curly.jpg",
    badge: "Vibrant Color Trend 🧡",
    description: "Inspired by the unforgettable golden-orange sunsets of Steiltes ridge. Rich burnt cinnamon and vibrant copper tones on thick, luscious deep wave curls.",
    blendDetails: "70% Human Hair + 30% Thermofiber Blend, pre-dyed with non-fade Lowveld UV protection",
    length: "24 Inch",
    lengths: ["18 Inch", "22 Inch", "24 Inch", "28 Inch"],
    colors: ["Burnt Copper #350", "Spiced Ginger Amber", "Auburn Highlight"],
    capType: "5x5 HD Glueless Closure with Adjustable Comb Clips",
    heatLimit: "Safe up to 180°C",
    inStock: true,
    featured: true,
  },
  {
    name: "Riverside Royalty 10\" Asymmetrical Blunt Cut Bob",
    slug: "riverside-royalty-10-inch-blunt-bob",
    category: "bobs",
    price: 599,
    originalPrice: 799,
    rating: "4.8",
    reviewCount: 31,
    image: "/images/hair-bob-pixie.jpg",
    badge: "Boss Babe Essential 💼",
    description: "Sharp as a razor blade. Put this on in 60 seconds flat before your corporate meeting or Nelspruit government district workday. Zero glue needed, pre-styled blunt edges.",
    blendDetails: "80% Fine Human Hair + 20% Form-Retaining Memory Fiber (never loses its sharp blunt cut)",
    length: "10 Inch",
    lengths: ["8 Inch", "10 Inch", "12 Inch"],
    colors: ["Natural 1B", "Jet Black #1", "Burgundy Tips 99J"],
    capType: "Glueless 4x4 Lace Closure with 3D Snug Band",
    heatLimit: "Safe up to 200°C",
    inStock: true,
    featured: true,
  },
  {
    name: "Honey Caramel Piano 26\" Body Wave #4/27 Highlight Unit",
    slug: "honey-caramel-piano-26-inch-body-wave",
    category: "colored",
    price: 920,
    originalPrice: 1250,
    rating: "5.0",
    reviewCount: 47,
    image: "/images/hair-highlight-wave.jpg",
    badge: "Most Requested In Salon 👑",
    description: "Stunning multidimensional caramel and honey blonde piano streaks woven through rich chocolate body waves. Looks effortlessly expensive and gives maximum volume.",
    blendDetails: "75% Virgin Human Hair + 25% Color-Locking Microfiber (highlights won't dull in the sun)",
    length: "26 Inch",
    lengths: ["20 Inch", "24 Inch", "26 Inch", "30 Inch"],
    colors: ["Piano Highlights #4/27", "Chocolate Toffee Balayage"],
    capType: "13x4 HD Glueless Lace Frontal",
    heatLimit: "Safe up to 190°C",
    inStock: true,
    featured: true,
  },
  {
    name: "Lowveld 3-Bundle Weave Pack (22\" + 24\" + 26\") Water Wave",
    slug: "lowveld-3-bundle-weave-pack-water-wave",
    category: "bundles",
    price: 750,
    originalPrice: 990,
    rating: "4.9",
    reviewCount: 56,
    image: "/images/hair-bundle-textures.jpg",
    badge: "Triple Value Bundle Pack 📦",
    description: "Three thick 100g bundles of juicy water wave human hair blend. Double-wefted to prevent shedding, silky smooth to the touch, ready for sew-in or custom wig making in Nelspruit.",
    blendDetails: "Cuticle-intact Human Hair blended with flex-curl fibers that snap back into wave pattern after wash",
    length: "22\" + 24\" + 26\"",
    lengths: ["18\"+20\"+22\"", "22\"+24\"+26\"", "26\"+28\"+30\""],
    colors: ["Natural 1B Black"],
    capType: "3x Weft Bundles (Closure optional add-on)",
    heatLimit: "Safe up to 190°C",
    inStock: true,
    featured: true,
  },
  {
    name: "Afro Kinky Goddess 22\" 4C Textured Glueless Unit",
    slug: "afro-kinky-goddess-22-inch-glueless",
    category: "glueless-wigs",
    price: 820,
    originalPrice: 1050,
    rating: "4.9",
    reviewCount: 22,
    image: "https://images.pexels.com/photos/32630320/pexels-photo-32630320.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    badge: "4C Natural Texture Match 🤎",
    description: "Mimics blown-out or twist-out 4B/4C natural texture with supreme softness. Huge volume, super lightweight, and completely natural hairline that fools everyone.",
    blendDetails: "70% Coarse Texture Human Hair + 30% Volumizing Air-Silk",
    length: "22 Inch",
    lengths: ["16 Inch", "20 Inch", "22 Inch", "26 Inch"],
    colors: ["Natural 1B", "Off Black #2"],
    capType: "5x5 HD Pre-Plucked Lace Closure",
    heatLimit: "Safe up to 180°C",
    inStock: true,
    featured: false,
  },
  {
    name: "2-Minute Slay 26\" Drawstring Ponytail & Wrap",
    slug: "2-minute-slay-26-inch-drawstring-ponytail",
    category: "ponytails",
    price: 350,
    originalPrice: 480,
    rating: "4.8",
    reviewCount: 64,
    image: "https://images.pexels.com/photos/15868320/pexels-photo-15868320.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    badge: "Quick 2-Minute Glam ⏱️",
    description: "Running late for church, university at UNIVEN/TUT campus, or lunch with the girls? Slick your natural hair into a bun, clip the two inner combs in, and pull the drawstring tight!",
    blendDetails: "High-grade human hair blend with secure built-in combs and Velcro wrap-around hair strand",
    length: "26 Inch",
    lengths: ["22 Inch", "26 Inch", "30 Inch"],
    colors: ["Natural 1B", "Honey Blonde Tips", "Chestnut #4"],
    capType: "Drawstring Cap with 2 Steel Combs & Velcro Wrap",
    heatLimit: "Safe up to 180°C",
    inStock: true,
    featured: false,
  },
  {
    name: "Burgundy 99J Seduction 26\" Deep Curly HD Unit",
    slug: "burgundy-99j-seduction-26-inch-deep-curly",
    category: "colored",
    price: 860,
    originalPrice: 1120,
    rating: "4.9",
    reviewCount: 19,
    image: "https://images.pexels.com/photos/12353138/pexels-photo-12353138.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    badge: "Deep Wine Glow 🍷",
    description: "Sultry, deep wine burgundy shade that complements all South African skin undertones. Bouncy corkscrew spirals that hold their shape even during a night out.",
    blendDetails: "70% Human Hair + 30% High Temperature Luster Fiber",
    length: "26 Inch",
    lengths: ["22 Inch", "26 Inch", "28 Inch"],
    colors: ["Wine Burgundy 99J", "Dark Plum Cherry"],
    capType: "13x4 HD Glueless Frontal",
    heatLimit: "Safe up to 180°C",
    inStock: true,
    featured: false,
  },
  {
    name: "Sonpark Chic 12\" Pixie Cut Glueless Human Blend",
    slug: "sonpark-chic-12-inch-pixie-cut",
    category: "bobs",
    price: 520,
    originalPrice: 680,
    rating: "4.7",
    reviewCount: 18,
    image: "https://images.pexels.com/photos/31622484/pexels-photo-31622484.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    badge: "Effortless & Classy ✂️",
    description: "Feathered layers, tapered neck, and effortless side-swept bangs. Perfect for mature queens and busy professionals who want to look put-together with zero styling time.",
    blendDetails: "85% Human Hair Blend with memory contouring cap",
    length: "12 Inch",
    lengths: ["10 Inch", "12 Inch"],
    colors: ["Natural 1B", "Salt & Pepper Grey Mix", "Honey Streaks"],
    capType: "Machine Weft with Breathable Rose Net & Stretch Band",
    heatLimit: "Safe up to 200°C",
    inStock: true,
    featured: false,
  },
  {
    name: "Lowveld Humidity-Shield Lace Melt Spray & Foam Duo",
    slug: "lowveld-humidity-shield-lace-melt-spray-foam",
    category: "care",
    price: 240,
    originalPrice: 320,
    rating: "5.0",
    reviewCount: 78,
    image: "https://images.pexels.com/photos/29824661/pexels-photo-29824661.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    badge: "Melt & Anti-Frizz Duo 💧",
    description: "Formulated specifically for Nelspruit's humid subtropical climate! Melting spray locks your lace without turning white or crusty, and the curl mousse rehydrates blend curls with zero alcohol dryness.",
    blendDetails: "Enriched with Aloe Vera, Argan Oil, and UV Filters (Alcohol-free & sweat resistant)",
    length: "200ml Spray + 150ml Mousse",
    lengths: ["Standard Duo Set"],
    colors: ["Clear / Invisible Hold"],
    capType: "Styling Care Product",
    heatLimit: "Heat Protector built-in",
    inStock: true,
    featured: false,
  },
  {
    name: "Satin Sleep & Crown Guard Bonnet + Edge Band Set",
    slug: "satin-sleep-crown-guard-bonnet-set",
    category: "care",
    price: 180,
    originalPrice: 240,
    rating: "4.9",
    reviewCount: 45,
    image: "https://images.pexels.com/photos/13221796/pexels-photo-13221796.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
    badge: "Hair Longevity Must-Have 🌙",
    description: "Double-layered mulberry satin bonnet with wide elastic edge grip band. Prevents friction, prevents dry ends, and keeps your human hair blend silky smooth for up to 18 months.",
    blendDetails: "100% Grade 6A Mulberry Satin Silk (Hypoallergenic)",
    length: "Extra Large (Fits up to 34\" wigs)",
    lengths: ["Extra Large Wide-Band"],
    colors: ["Rose Gold & Black Reversible", "Champagne Gold & Emerald"],
    capType: "Hair Care Accessory",
    heatLimit: "N/A",
    inStock: true,
    featured: false,
  },
];

export const initialReviews = [
  {
    customerName: "Nompumelelo Sithole",
    suburb: "West Acres, Nelspruit",
    rating: 5,
    wigStyle: "The Lowveld Bounce 28\" Wet & Wavy",
    comment: "Yoh bathong! Nelspruit was 37 degrees last Saturday and my curls did not drop even once at the family braai. People were asking me if I paid R4,500 at Sandton City for this hair! I love that I could pick it up at Sonpark Centre within 2 hours of ordering. 10/10!",
    verifiedLocation: "Nelspruit (Collected at Sonpark)",
    likesCount: 34,
  },
  {
    customerName: "Thandiwe Khumalo",
    suburb: "Steiltes, Nelspruit",
    rating: 5,
    wigStyle: "Mbombela Bone Straight 30\"",
    comment: "I was skeptical about human hair blends until I washed this unit. The water just brought the shine out, and when I flat ironed it at 190°C it got bone straight like glass! Same-day delivery to Steiltes was on point. Definitely my new go-to hair plug.",
    verifiedLocation: "Nelspruit (Same-Day Delivery)",
    likesCount: 28,
  },
  {
    customerName: "Lindiwe Ndlovu",
    suburb: "Riverside Park, Nelspruit",
    rating: 5,
    wigStyle: "Sunset In Steiltes Copper Ginger",
    comment: "The ginger color is giving main character energy! Compliments left and right at work in Riverside. The HD lace really melted into my skin with their melt spray, zero white cast. Will be ordering the wet & wavy next month!",
    verifiedLocation: "Riverside, Nelspruit",
    likesCount: 19,
  },
  {
    customerName: "Chantelle Van Der Merwe",
    suburb: "White River / Nelspruit Border",
    rating: 5,
    wigStyle: "Riverside Royalty 10\" Blunt Bob",
    comment: "The cut on this bob is perfection. As a teacher I need something smart and fast in the mornings. Pop it on, brush, done. High quality blend that doesn't tangle at the nape like cheap synthetics.",
    verifiedLocation: "White River, Mpumalanga",
    likesCount: 15,
  },
  {
    customerName: "Busisiwe Maseko",
    suburb: "Kamagugu, Nelspruit",
    rating: 5,
    wigStyle: "Honey Caramel Piano 26\" Body Wave",
    comment: "Super full density, no weird smell, and soft like butter. Nelspruit ladies, don't sleep on this shop! PayFlex 4 installments made it so easy to budget.",
    verifiedLocation: "Kamagugu, Nelspruit",
    likesCount: 41,
  },
];

export async function seedDatabase() {
  const existingProducts = await db.select().from(products);
  if (existingProducts.length === 0) {
    console.log("Seeding products...");
    await db.insert(products).values(initialProducts);
  }

  const existingReviews = await db.select().from(reviews);
  if (existingReviews.length === 0) {
    console.log("Seeding reviews...");
    await db.insert(reviews).values(initialReviews);
  }

  const existingOrders = await db.select().from(orders);
  if (existingOrders.length === 0) {
    console.log("Seeding initial sample order...");
    await db.insert(orders).values([
      {
        orderNumber: "NEL-8921",
        customerName: "Precious Dlamini",
        customerPhone: "072 345 6789",
        customerEmail: "precious.d@gmail.com",
        suburb: "West Acres",
        streetAddress: "14 Koraalboom Avenue",
        city: "Nelspruit",
        deliveryMethod: "same_day_nelspruit",
        paymentMethod: "instant_eft",
        items: [
          {
            id: 1,
            name: "The Lowveld Bounce 28\" Wet & Wavy HD Glueless Unit",
            price: 899,
            quantity: 1,
            length: "28 Inch",
            color: "Natural 1B Jet Black",
            image: "/images/hero-hair-baddie.jpg",
          },
        ],
        subtotal: 899,
        discount: 0,
        shippingFee: 60,
        total: 959,
        status: "Out For Delivery",
        notes: "Please call when near West Acres Shopping Centre",
      },
    ]);
  }

  const existingAppointments = await db.select().from(appointments);
  if (existingAppointments.length === 0) {
    console.log("Seeding sample appointment...");
    await db.insert(appointments).values([
      {
        customerName: "Zandile Mokoena",
        customerPhone: "083 456 7890",
        customerEmail: "zandile.m@yahoo.com",
        service: "Wig Fitting & Lace Tinting",
        preferredDate: "Tomorrow",
        preferredTime: "14:00 - 14:30",
        suburb: "Sonpark / Nelspruit Central",
        notes: "Interested in the 30\" bone straight unit.",
        status: "Confirmed",
      },
    ]);
  }
}
